name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install pytest pytest-cov flake8 mypy codecov
    - name: Lint with flake8
      run: |
        flake8 human_readable_cron --count --select=E9,F63,F7,F82 --show-source --statistics
    - name: Type check with mypy
      run: |
        mypy human_readable_cron --exclude human_readable_cron/tests
    - name: Generate coverage report
      run: |
        pytest --cov-branch --cov-report=xml